CREATE DATABASE IF NOT EXISTS appdb;
USE appdb;
CREATE TABLE IF NOT EXISTS sample (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100)
);
INSERT INTO sample (name) VALUES ('Alice'),('Bob') ON DUPLICATE KEY UPDATE name=name;
